# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_UNOSwindow(object):
    def setupUi(self, UNOSwindow):
        UNOSwindow.setObjectName("UNOSwindow")
        UNOSwindow.resize(800, 480)
        self.centralwidget = QtWidgets.QWidget(UNOSwindow)
        self.centralwidget.setObjectName("centralwidget")
        self.titleLabel = QtWidgets.QLabel(self.centralwidget)
        self.titleLabel.setGeometry(QtCore.QRect(0, 0, 801, 61))
        font = QtGui.QFont()
        font.setFamily("Industry-Book")
        font.setPointSize(21)
        self.titleLabel.setFont(font)
        self.titleLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.titleLabel.setObjectName("titleLabel")
        self.activateButton = QtWidgets.QPushButton(self.centralwidget)
        self.activateButton.setGeometry(QtCore.QRect(30, 350, 251, 71))
        font = QtGui.QFont()
        font.setFamily("Industry-Book")
        font.setPointSize(22)
        self.activateButton.setFont(font)
        self.activateButton.setObjectName("activateButton")
        self.unosOutput = QtWidgets.QTextBrowser(self.centralwidget)
        self.unosOutput.setGeometry(QtCore.QRect(300, 70, 481, 351))
        self.unosOutput.setObjectName("unosOutput")
        self.configOutput = QtWidgets.QTextBrowser(self.centralwidget)
        self.configOutput.setGeometry(QtCore.QRect(30, 70, 251, 231))
        self.configOutput.setObjectName("configOutput")
        self.statusText = QtWidgets.QLabel(self.centralwidget)
        self.statusText.setGeometry(QtCore.QRect(30, 310, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Industry-Book")
        font.setPointSize(14)
        self.statusText.setFont(font)
        self.statusText.setAlignment(QtCore.Qt.AlignCenter)
        self.statusText.setObjectName("statusText")
        self.statusLabel = QtWidgets.QLabel(self.centralwidget)
        self.statusLabel.setGeometry(QtCore.QRect(120, 310, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Industry-Book")
        font.setPointSize(14)
        self.statusLabel.setFont(font)
        self.statusLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.statusLabel.setObjectName("statusLabel")
        UNOSwindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(UNOSwindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        self.systemMenu = QtWidgets.QMenu(self.menubar)
        self.systemMenu.setObjectName("systemMenu")
        self.helpMenu = QtWidgets.QMenu(self.menubar)
        self.helpMenu.setObjectName("helpMenu")
        UNOSwindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(UNOSwindow)
        self.statusbar.setObjectName("statusbar")
        UNOSwindow.setStatusBar(self.statusbar)
        self.actionAbout_UNOS = QtWidgets.QAction(UNOSwindow)
        self.actionAbout_UNOS.setObjectName("actionAbout_UNOS")
        self.preferencesButton = QtWidgets.QAction(UNOSwindow)
        self.preferencesButton.setObjectName("preferencesButton")
        self.aboutButton = QtWidgets.QAction(UNOSwindow)
        self.aboutButton.setObjectName("aboutButton")
        self.troubleshootingButton = QtWidgets.QAction(UNOSwindow)
        self.troubleshootingButton.setObjectName("troubleshootingButton")
        self.systemMenu.addAction(self.preferencesButton)
        self.helpMenu.addAction(self.aboutButton)
        self.helpMenu.addSeparator()
        self.helpMenu.addAction(self.troubleshootingButton)
        self.menubar.addAction(self.systemMenu.menuAction())
        self.menubar.addAction(self.helpMenu.menuAction())

        self.retranslateUi(UNOSwindow)
        QtCore.QMetaObject.connectSlotsByName(UNOSwindow)

    def retranslateUi(self, UNOSwindow):
        _translate = QtCore.QCoreApplication.translate
        UNOSwindow.setWindowTitle(_translate("UNOSwindow", "UNOS Assistant Launch Center"))
        self.titleLabel.setText(_translate("UNOSwindow", "UNOS Assistant Launch Center ( Version 0.0.3 )"))
        self.activateButton.setText(_translate("UNOSwindow", "ON / OFF"))
        self.statusText.setText(_translate("UNOSwindow", "STATUS: "))
        self.statusLabel.setText(_translate("UNOSwindow", "DEACTIVATED"))
        self.systemMenu.setTitle(_translate("UNOSwindow", "System"))
        self.helpMenu.setTitle(_translate("UNOSwindow", "Help"))
        self.actionAbout_UNOS.setText(_translate("UNOSwindow", "About UNOS"))
        self.preferencesButton.setText(_translate("UNOSwindow", "Preferences"))
        self.aboutButton.setText(_translate("UNOSwindow", "About UNOS"))
        self.troubleshootingButton.setText(_translate("UNOSwindow", "Troubleshooting"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    UNOSwindow = QtWidgets.QMainWindow()
    ui = Ui_UNOSwindow()
    ui.setupUi(UNOSwindow)
    UNOSwindow.show()
    sys.exit(app.exec_())
